[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "REPLACE WITH YOUR OWN COOKIE SECRET"
client_id = "REPLACE WITH YOUR OWN GOOGLE OAUTH CLIENT ID"
client_secret = "REPLACE WITH YOUR OWN GOOGLE OAUTH CLIENT SECRET"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
